import os
import re

target_file = r"D:\ucberkeley\EverMemOs\EverMemOS\ever_tutor\app.py"

with open(target_file, "r", encoding="utf-8") as f:
    content = f.read()

# I will find the landing page block up to # 2. MAIN APPLICATION
start_marker = "# 1. LANDING PAGE"
end_marker = "# 2. MAIN APPLICATION"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print("Could not find markers.")
else:
    # Backtrack start_idx to the # ------ line
    actual_start_idx = content.rfind("# ---", 0, start_idx)

    new_landing = """# ---------------------------------------------------------
# 1. LANDING PAGE (DENSE BRAIN STARLINK BACKGROUND)
# ---------------------------------------------------------
import streamlit.components.v1 as components

if not st.session_state.app_started:
    st.markdown('''
    <style>
    /* Hide default Streamlit elements */
    [data-testid="stSidebar"] { display: none !important; }
    [data-testid="collapsedControl"] { display: none !important; }
    header[data-testid="stHeader"] { display: none !important; }
    .stApp > header { display: none !important; }
    
    /* Make app full dark */
    .stApp {
        background-color: #020617 !important;
        overflow: hidden;
    }
    
    /* Remove padding to let background be flush */
    .block-container {
        padding: 0 !important;
        max-width: 100% !important;
    }
    
    /* Target the iframe container natively generated by Streamlit to make it fixed */
    iframe {
        position: fixed !important;
        top: 0;
        left: 0;
        width: 100vw !important;
        height: 100vh !important;
        z-index: 0 !important;
        border: none !important;
        pointer-events: auto !important;
    }

    /* Absolute positioning for the Streamlit button container */
    div.stButton {
        position: fixed;
        top: 75vh;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 99999 !important;
        text-align: center;
        display: flex;
        justify-content: center;
    }
    
    div.stButton > button {
        border-radius: 50px !important;
        padding: 1rem 4rem !important;
        font-size: 1.5rem !important;
        font-weight: 800 !important;
        background: rgba(14, 165, 233, 0.15) !important;
        border: 2px solid rgba(56, 189, 248, 0.6) !important;
        color: #f0f9ff !important;
        backdrop-filter: blur(10px) !important;
        box-shadow: 0 0 25px rgba(14, 165, 233, 0.3), inset 0 0 15px rgba(14, 165, 233, 0.2) !important;
        transition: all 0.3s ease !important;
        text-transform: uppercase;
        letter-spacing: 3px;
        cursor: pointer;
    }
    div.stButton > button:hover {
        transform: scale(1.05) translateY(-2px) !important;
        background: rgba(14, 165, 233, 0.4) !important;
        box-shadow: 0 0 40px rgba(56, 189, 248, 0.6), inset 0 0 25px rgba(56, 189, 248, 0.4) !important;
        border-color: rgba(125, 211, 252, 1) !important;
        color: #ffffff !important;
    }
    div.stButton > button:active {
        transform: scale(0.95) !important;
    }
    </style>
    ''', unsafe_allow_html=True)

    html_code = '''
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <style>
            body { margin: 0; padding: 0; background-color: #020617; overflow: hidden; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
            #canvas-container { width: 100vw; height: 100vh; position: absolute; top: 0; left: 0; z-index: 1; }
            #overlay { position: absolute; top: 35%; left: 50%; transform: translate(-50%, -50%); z-index: 10; text-align: center; pointer-events: none; width: 100%; }
            .title { font-size: 5rem; font-weight: 800; background: linear-gradient(135deg, #e0f2fe, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin: 0; letter-spacing: -1px; text-shadow: 0 0 30px rgba(56,189,248,0.3); animation: pulse 4s infinite alternate; }
            .subtitle { font-size: 1.5rem; color: #94a3b8; margin-top: 1rem; font-weight: 400; letter-spacing: 2px; text-transform: uppercase;}
            @keyframes pulse { 0% { filter: brightness(1) drop-shadow(0 0 10px rgba(56,189,248,0.2)); } 100% { filter: brightness(1.2) drop-shadow(0 0 30px rgba(56,189,248,0.5)); } }
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    </head>
    <body>
        <div id="overlay">
            <h1 class="title">EverMemOS</h1>
            <p class="subtitle">Cognitive Neural Networking System</p>
        </div>
        <div id="canvas-container"></div>
        <script>
            const scene = new THREE.Scene();
            scene.fog = new THREE.FogExp2('#020617', 0.001);
            
            const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 1, 3000);
            camera.position.z = 800;

            const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
            renderer.setSize(window.innerWidth, window.innerHeight);
            renderer.setClearColor('#020617', 1);
            document.getElementById('canvas-container').appendChild(renderer.domElement);

            const particleCount = 2000;
            const geometry = new THREE.BufferGeometry();
            const positions = new Float32Array(particleCount * 3);
            const sizes = new Float32Array(particleCount);
            
            for(let i = 0; i < particleCount; i++) {
                let theta = Math.random() * Math.PI * 2;
                let phi = Math.acos((Math.random() * 2) - 1);
                
                let r = 250 + Math.random() * 150;
                
                if (Math.abs(Math.sin(theta)) < 0.3) {
                    r *= 0.6 + (Math.abs(Math.sin(theta)) * 1.3);
                }
                if (Math.cos(phi) < -0.5) {
                    r *= 0.8;
                }

                let x = r * Math.sin(phi) * Math.cos(theta);
                let y = r * Math.cos(phi);
                let z = r * Math.sin(phi) * Math.sin(theta);
                
                x += (Math.random() - 0.5) * 40;
                y += (Math.random() - 0.5) * 40;
                z += (Math.random() - 0.5) * 40;

                positions[i*3] = x;
                positions[i*3+1] = y;
                positions[i*3+2] = z;
                
                sizes[i] = Math.random() * 2 + 1;
            }

            geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
            geometry.setAttribute('size', new THREE.BufferAttribute(sizes, 1));

            const material = new THREE.PointsMaterial({
                color: 0x38bdf8,
                size: 2.5,
                transparent: true,
                opacity: 0.8,
                blending: THREE.AdditiveBlending
            });

            const particles = new THREE.Points(geometry, material);
            scene.add(particles);

            const lineMaterial = new THREE.LineBasicMaterial({
                color: 0x0ea5e9,
                transparent: true,
                opacity: 0.15,
                blending: THREE.AdditiveBlending
            });
            
            const lineGeo = new THREE.BufferGeometry();
            const linePos = [];
            const p = positions;
            const maxConnectDist = 65;
            
            for(let i=0; i<particleCount; i++) {
                let nodeConnects = 0;
                for(let j=i+1; j<particleCount; j++) {
                    if(nodeConnects > 4) break;
                    let dx = p[i*3] - p[j*3];
                    let dy = p[i*3+1] - p[j*3+1];
                    let dz = p[i*3+2] - p[j*3+2];
                    let dist = Math.sqrt(dx*dx + dy*dy + dz*dz);
                    
                    if(dist < maxConnectDist) {
                        linePos.push(p[i*3], p[i*3+1], p[i*3+2]);
                        linePos.push(p[j*3], p[j*3+1], p[j*3+2]);
                        nodeConnects++;
                    }
                }
            }
            lineGeo.setAttribute('position', new THREE.Float32BufferAttribute(linePos, 3));
            const lines = new THREE.LineSegments(lineGeo, lineMaterial);
            scene.add(lines);

            const glowGeo = new THREE.SphereGeometry(200, 32, 32);
            const glowMat = new THREE.MeshBasicMaterial({
                color: 0x0369a1,
                transparent: true,
                opacity: 0.05,
                blending: THREE.AdditiveBlending
            });
            const glowMesh = new THREE.Mesh(glowGeo, glowMat);
            scene.add(glowMesh);

            let mouseX = 0;
            let mouseY = 0;
            document.addEventListener('mousemove', (event) => {
                mouseX = (event.clientX - window.innerWidth / 2) * 1.5;
                mouseY = (event.clientY - window.innerHeight / 2) * 1.5;
            });

            window.addEventListener('resize', () => {
                camera.aspect = window.innerWidth / window.innerHeight;
                camera.updateProjectionMatrix();
                renderer.setSize(window.innerWidth, window.innerHeight);
            });

            let time = 0;
            function animate() {
                requestAnimationFrame(animate);
                time += 0.002;
                
                particles.rotation.y = time * 0.5;
                particles.rotation.z = time * 0.2;
                lines.rotation.y = time * 0.5;
                lines.rotation.z = time * 0.2;
                
                let pulseBase = 1 + (Math.sin(time * 15) * 0.02);
                particles.scale.set(pulseBase, pulseBase, pulseBase);
                lines.scale.set(pulseBase, pulseBase, pulseBase);
                glowMesh.scale.set(pulseBase*1.2, pulseBase*1.2, pulseBase*1.2);

                camera.position.x += (mouseX - camera.position.x) * 0.05;
                camera.position.y += (-mouseY - camera.position.y) * 0.05;
                camera.lookAt(scene.position);

                renderer.render(scene, camera);
            }
            animate();
        </script>
    </body>
    </html>
    '''
    
    # 1. Render background HTML natively to screen with fixed width/height 0 Streamlit layout
    components.html(html_code, height=0)
    
    # 2. Render actual Button. It will be positioned fixed automatically via the CSS above
    if st.button("INITIATE LINK"):
        st.session_state.app_started = True
        st.rerun()

"""
    
    # Actually end_idx is exactly at "# 2. MAIN APPLICATION"
    # Find original "2. MAIN APPLICATION" start block
    actual_end_idx = content.rfind("# ---", start_idx, end_idx)
    
    new_source = content[:actual_start_idx] + new_landing + content[actual_end_idx:]
    
    with open(target_file, "w", encoding="utf-8") as f:
        f.write(new_source)

    print("Success!")
